configure: rearrange and set CXX on openbsd

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,30 +14,13 @@ type llvm-config
 type jam
 echo
 
-# C++11 required.
-${CXX-c++} -x c++ -std=c++11 -E - < /dev/null > /dev/null
-
-# citrun_gltest needs osmesa and both it and citrun_gl need the rest.
-gl_pkgs="osmesa glfw3 glew freetype2"
-for pkg in $gl_pkgs; do
-	printf "%10s = " $pkg
-	pkg-config --modversion $pkg || (echo "not found" && exit 1)
-done
-
-# citrun_inst needs clang and llvm libraries.
-CLANG_LIBS="-lclangAST -lclangAnalysis -lclangBasic -lclangDriver \
-	-lclangEdit -lclangFrontend -lclangFrontendTool -lclangLex \
-	-lclangParse -lclangRewrite -lclangRewriteFrontend -lclangSema \
-	-lclangSerialization -lclangTooling"
-
-LLVM_LIBS="bitreader mcparser transformutils option"
-
 # Operating system specific variables.
 uname=`uname`
 if [ $uname = OpenBSD ]; then
 	LDGROUP_START="-Wl,--start-group"
 	LDGROUP_END="-Wl,--end-group"
 	FONT_PATH="/usr/X11R6/lib/X11/fonts/TTF/DejaVuSansMono.ttf"
+	CXX=eg++
 elif [ $uname = Darwin ]; then
 	GL_EXTRALIB="-framework OpenGL"
 	FONT_PATH="/Library/Fonts/Andale Mono.ttf"
@@ -49,8 +32,27 @@ elif [ $uname = Linux ]; then
 	FONT_PATH="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
 else
 	echo WARNING: Platform $uname not tested. Compilation may fail.
+	echo
 fi
+
+# C++11 required.
+${CXX-c++} -x c++ -std=c++11 -E - < /dev/null > /dev/null
+
+# citrun_gltest needs osmesa and both it and citrun_gl need the rest.
+gl_pkgs="osmesa glfw3 glew freetype2"
+for pkg in $gl_pkgs; do
+	printf "%10s = " $pkg
+	pkg-config --modversion $pkg || (echo "not found" && exit 1)
+done
 echo
+
+# citrun_inst needs clang and llvm libraries.
+CLANG_LIBS="-lclangAST -lclangAnalysis -lclangBasic -lclangDriver \
+	-lclangEdit -lclangFrontend -lclangFrontendTool -lclangLex \
+	-lclangParse -lclangRewrite -lclangRewriteFrontend -lclangSema \
+	-lclangSerialization -lclangTooling"
+
+LLVM_LIBS="bitreader mcparser transformutils option"
 
 # Write top of Jamrules. Any errors inside backticks get ignored.
 cat <<EOF > Jamrules
