src: move the rest of Jamrules.in into configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 # ░█░░░░░░█░░░█░░░░█▀▄░█░█░█░█
 # ░▀▀▀░░░▀▀▀░░▀░░░░▀░▀░▀▀▀░▀░▀
 #
-# Creates Jamrules from Jamrules.in and output from this script.
+# Creates Jamrules.
 #
 type pkg-config
 type llvm-config
@@ -18,12 +18,29 @@ type llvm-config
 # - OpenGLES >= 2.0
 
 gl_pkgs="osmesa glfw3 glew freetype2"
-pkg-config --exists $gl_pkgs
 
-cp Jamrules.in Jamrules
-cat <<EOF >> Jamrules
+should_exit=0
+for pkg in $gl_pkgs; do
+	if ! pkg-config --exists $pkg; then
+		echo "$pkg not found"
+		should_exit=1
+	fi
+done
+test $should_exit -eq 0 || exit 1
 
-# Automatically generated on `date`
+cat <<EOF > Jamrules
+#
+# Generated by './configure' on `date`
+#
+echo ...build C It Run on \$(OS)... ;
+
+CC = ${CC-cc} ;
+C++ = ${CXX-c++} ;
+
+CCFLAGS += "${CFLAGS-}" ;
+C++FLAGS += -std=c++11 -fno-exceptions -fno-rtti ${CFLAGS-} ;
+LINKFLAGS += "${LDFLAGS-}" ;
+
 CITRUN_SRCDIR = "`pwd`/src" ;
 
 GL_CFLAGS = "`pkg-config --cflags glfw3 glew freetype2`" ;
@@ -34,6 +51,21 @@ INST_CFLAGS = "`llvm-config --cxxflags`" ;
 INST_LDFLAGS = "`llvm-config --ldflags`" ;
 INST_LIBS = "`llvm-config --libs bitreader mcparser transformutils option`" ;
 INST_LIBS += "`llvm-config --system-libs`" ;
+
+if \$(OS) = OPENBSD {
+	LDGROUP_START = -Wl,--start-group ;
+	LDGROUP_END = -Wl,--end-group ;
+}
+
+if \$(OS) = MACOSX {
+	LINKLIBS on citrun-gl = -framework OpenGL ;
+}
+
+if \$(OS) = LINUX {
+	LINKLIBS on citrun-gl citrun-inst = -lbsd ;
+	LDGROUP_START = -Wl,--start-group ;
+	LDGROUP_END = -Wl,--end-group ;
+}
 EOF
 
-echo ">> Jamrules created. Now run \`jam\` to build"
+echo "...call \`jam\` to build..."
