src: move CLANG_LIBS into configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,43 +1,50 @@
 #!/bin/sh -eu
 #
-# ░█▀▀░░░▀█▀░▀█▀░░░█▀▄░█░█░█▀█
-# ░█░░░░░░█░░░█░░░░█▀▄░█░█░█░█
-# ░▀▀▀░░░▀▀▀░░▀░░░░▀░▀░▀▀▀░▀░▀
+# Checks that a bunch of crap is installed, creates Jamrules file.
 #
-# Creates Jamrules file.
-#
+uname=`uname`
+echo ░█▀▀░░░▀█▀░▀█▀░░░█▀▄░█░█░█▀█
+echo ░█░░░░░░█░░░█░░░░█▀▄░█░█░█░█
+echo ░▀▀▀░░░▀▀▀░░▀░░░░▀░▀░▀▀▀░▀░▀
+echo C It Run 0.0 on $uname
+echo
+
+# These binaries are assumed throughout so make sure they are available.
 type pkg-config
 type llvm-config
+type jam
+echo
 
-#
-# Check for C++11 compiler.
-#
-touch __test.cc
-${CXX-c++} -std=c++11 -c __test.cc
+# C++11 required.
+${CXX-c++} -x c++ -std=c++11 -E - < /dev/null > /dev/null
 
-#
-# llvm/clang versions must be >= 3.7
-#
-llvm-config --version
-
-#
-# Check for pkg-config available software. Try and print a nice missing list.
-#
+# citrun-gltest needs osmesa and both it and citrun-gl need the rest.
 gl_pkgs="osmesa glfw3 glew freetype2"
-
-should_exit=0
 for pkg in $gl_pkgs; do
-	if ! pkg-config --exists $pkg; then
-		echo "$pkg not found"
-		should_exit=1
-	fi
+	printf "%10s = " $pkg
+	pkg-config --modversion $pkg || (echo "not found" && exit 1)
 done
-test $should_exit -eq 0 || exit 1
+echo
 
-#
-# Write Jamrules which consists of {llvm,pkg}-config calls getting various flags
-# and library names. Note any errors inside backticks will be ignored.
-#
+if [ $uname = OpenBSD ]; then
+	LDGROUP_START="-Wl,--start-group"
+	LDGROUP_END="-Wl,--end-group"
+	FONT_PATH="/usr/X11R6/lib/X11/fonts/TTF/DejaVuSansMono.ttf"
+elif [ $uname = Darwin ]; then
+	GL_EXTRALIB="-framework OpenGL"
+	FONT_PATH="/Library/Fonts/Andale Mono.ttf"
+elif [ $uname = Linux ]; then
+	GL_EXTRALIB="-lbsd"
+	INST_EXTRALIB="-lbsd"
+	LDGROUP_START="-Wl,--start-group"
+	LDGROUP_END="-Wl,--end-group"
+	FONT_PATH="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
+else
+	echo WARNING: Platform $uname not tested. Compilation may fail.
+	echo
+fi
+
+# Write top of Jamrules. Note any errors inside backticks will be ignored.
 cat <<EOF > Jamrules
 CC = ${CC-cc} ;
 C++ = ${CXX-c++} ;
@@ -46,46 +53,25 @@ CCFLAGS += "${CFLAGS-}" ;
 C++FLAGS += -std=c++11 -fno-exceptions -fno-rtti ${CFLAGS-} ;
 LINKFLAGS += "${LDFLAGS-}" ;
 
+FONT_PATH = "${FONT_PATH}" ;
 CITRUN_SRCDIR = "`pwd`/src" ;
 
 GL_CFLAGS = "`pkg-config --cflags glfw3 glew freetype2`" ;
-GL_LIBS = "`pkg-config --libs glfw3 glew freetype2`" ;
+GL_LIBS = "${GL_EXTRALIB-} `pkg-config --libs glfw3 glew freetype2`" ;
 GLTEST_LIBS  = "`pkg-config --libs osmesa`" ;
 
 INST_CFLAGS = "`llvm-config --cxxflags`" ;
 INST_LDFLAGS = "`llvm-config --ldflags`" ;
-INST_LIBS = "`llvm-config --libs bitreader mcparser transformutils option`" ;
-INST_LIBS += "`llvm-config --system-libs`" ;
-
-# Generated by './configure' on `date`
-echo ...build C It Run on \$(OS)... ;
-
-if \$(OS) = OPENBSD {
-	LDGROUP_START = -Wl,--start-group ;
-	LDGROUP_END = -Wl,--end-group ;
-	FONT_PATH = "/usr/X11R6/lib/X11/fonts/TTF/DejaVuSansMono.ttf" ;
-}
-else if \$(OS) = MACOSX {
-	LINKLIBS on citrun-gl = -framework OpenGL ;
-	FONT_PATH "/Library/Fonts/Andale Mono.ttf" ;
-}
-else if \$(OS) = LINUX {
-	LINKLIBS on citrun-gl citrun-inst = -lbsd ;
-	LDGROUP_START = -Wl,--start-group ;
-	LDGROUP_END = -Wl,--end-group ;
-	FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf" ;
-}
-else {
-	echo "WARNING: FONT_PATH not configured" ;
-}
-
+INST_LIBS = "${INST_EXTRALIB-} ${LDGROUP_START-} -lclangAST -lclangAnalysis \
+-lclangBasic -lclangDriver \
+-lclangEdit -lclangFrontend -lclangFrontendTool -lclangLex -lclangParse \
+-lclangRewrite -lclangRewriteFrontend -lclangSema -lclangSerialization \
+-lclangTooling ${LDGROUP_END-} \
+`llvm-config --libs bitreader mcparser transformutils option` \
+`llvm-config --system-libs`" ;
 EOF
+echo === Configuration Summary ===================================================
+cat Jamrules
+echo =============================================================================
 
 cat Jamrules.tail >> Jamrules
-
-echo
-echo === Configuration Summary ==============================================
-head -n 8 Jamrules
-echo ========================================================================
-echo
-echo "...call \`jam\` to build..."
